# Generated by Django 5.1.2 on 2024-10-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
